version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: senha
      MYSQL_DATABASE: meu_banco
    volumes:
      - "./app:/app"
    restart: on-failure:5
  
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: meu_banco
    volumes:
      - meu_volume:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: senha


volumes:
  meu_volume:
    external: true
